// ── Discharge data — mirrors backend/mock_data/discharge_state.json exactly ──

export interface PatientProfile {
  procedure: string;
  discharge_date: string;
  attending_physician: string;
}

export interface Medication {
  name: string;
  dosage: string;
  frequency: string;
  instructions: string;
  domain_flags: string[];
}

export interface Restriction {
  category: string;
  rule: string;
  timeline?: string;
  strict_prohibitions?: string[];
  sandbox_trigger?: string;
}

export interface WarnSign {
  symptom: string;
  implication: string;
  action: string;
}

export interface DischargeState {
  patient_profile: PatientProfile;
  medications: Medication[];
  restrictions: Restriction[];
  warning_signs: WarnSign[];
}

// ── Navigation ──

export type PanelId =
  | "overview"
  | "medications"
  | "restrictions"
  | "warnings"
  | "ask";

// ── Agent room IDs (one-on-one voice/text rooms) ──

export type AgentRoomId = "medication-room" | "recovery-room" | "emergency-room";

// ── Room-based navigation ──

export type RoomId =
  | "lounge"
  | "medication-room"
  | "recovery-room"
  | "emergency-room"
  | "pt-studio"
  | "overview"
  | "medications"
  | "restrictions"
  | "warning-signs";

export type AgentName = "Medication Agent" | "Recovery Agent" | "Emergency Agent";

// ── Lounge messages (Slack-style group feed) ──

export interface LoungeMessage {
  id: string;
  agent: AgentName | "user";
  text: string;
  timestamp: number;
}

// ── Agent room messages (bubble-style 1-on-1) ──

export interface RoomMessage {
  id: string;
  role: "user" | "agent";
  text: string;
  timestamp: number;
}

// ── Conversation (Ask panel) ──

export interface ConversationTurn {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: number;
  /** Which domain the router classified this under */
  domain?: string;
}

// ── Medication visual (generated by Modal sandbox tool call) ──

export interface ScheduledMedication {
  name: string;
  dosage: string;
  frequency: string;
  instructions: string;
  color: string;
}

export type SlotId = "morning" | "afternoon" | "evening" | "night";

export interface ScheduleSlot {
  slot_id: SlotId;
  label: string;
  hours: string;
  color: string;
  medications: ScheduledMedication[];
}

export interface VisualData {
  image_base64: string;
  schedule: ScheduleSlot[];
  medication_count: number;
}

// ── Care Team Activity (RightPanel) ──

export type ActivityRoute =
  | "medications"
  | "recovery"
  | "emergency"
  | "confer"
  | "blocked";

export interface ActivityEntry {
  id: string;
  timestamp: number;
  route: ActivityRoute;
  audio_text: string;
  off_topic: boolean;
}
